### ISSUE TITLE
Safe for GTA:Online

### ISSUE THREAD

**Issue by maykimas** [NarutoUA/gta5_fsr#1]
Hi, thanks for this awesome news, i got a question: Is safe use it in GTA Online? Thanks

**Comment by informatorius** [comment]
Can the shaders be ported to Reshade extension? Because Reshade would be safe for online

**Comment by yasinallana** [comment]
Yes it should be safe since it is not an injection just a simple graphic setting

**Comment by NarutoUA** [comment]
In general: yes, but I dont know how GTA:O anticheat works so I dont guarantee you wont get banned. I will add more details on GTA:Online later with next update

**Comment by NarutoUA** [comment]
Check README for GTA Online information

**Comment by maykimas** [comment]
Thanks for stay updating

**Comment by yishouhaoshi3DM** [comment]
thanks for your work,how about now the safe of gta OL
