### ISSUE TITLE
FSR 3

### ISSUE THREAD

**Issue by NIUFT** [NarutoUA/gta5_fsr#106]

**Comment by Ririshi** [comment]
Very interested to see if this would be possible now that the FSR3 source code is openly available!

https://github.com/GPUOpen-LibrariesAndSDKs/FidelityFX-SDK/releases/tag/fsr3-v3.0.3

**Comment by Blazepoint5** [comment]
I hope the dude can use this so the fps would look awesome

**Comment by NarutoUA** [comment]
FSR 3 is DirectX12/Vulkan only

**Comment by 3laar** [comment]
I guess it could only be done if someone used the leaked source code, modified it to use DX12/Vulkan, and added ray tracing, DLSS, FidelityFX Super Resolution (FSR) 3 natively, rather than using mods. But this seems too good to be true.
