### ISSUE TITLE
What about downscaling e.g. frame scaling mode 1.5 ?

### ISSUE THREAD

**Issue by informatorius** [NarutoUA/gta5_fsr#12]
Does this also improve image quality on downscaling e.g. frame scaling mode 1.5 ?

**Comment by NarutoUA** [comment]
No, it doesn't. FSR is not about downscaling.

**Comment by informatorius** [comment]
But still in frame scaling mode 1.5 the FSR scaler is then used right?

**Comment by NarutoUA** [comment]
Mod only works for 0.5, 0.667, 0.75, 0.883. It stops working if scaling is off or above 1.0

**Comment by informatorius** [comment]
Would it be possible to also allow values above 1.0 to see the effect then?

Usecase would be e.g. a Full HD display where you still want GTA V engine to render at higher frame scale 1.5 to get more details and sharpness.
