### ISSUE TITLE
Works on GTX660?

### ISSUE THREAD

**Issue by doraimon0** [NarutoUA/gta5_fsr#14]
Well i tested this mod with nvidia GTX660 but i'm not sure if it works.

I did not notice any diffrence, probably because i'm playing at 720P lol

anyways i just wanted to say that this may work on nvidia old GPU's too but someone with high res monitor could try this out.

here is the log file, it says it worked :)
[GTX660.LOG](https://github.com/NarutoUA/gta5_fsr/files/6760294/GTX660.LOG)

I'm not complaining about anything, all i say that this may work on older gpu's too.

Thank you for this great mod :)

**Comment by maykimas** [comment]
Hi, you must activate MSAA, and remove semicolon before hotkey, 114. In game, advanced settings choose scaling factor.

**Comment by NarutoUA** [comment]
> anyways i just wanted to say that this may work on nvidia old GPU's too but someone with high res monitor could try this out.
Remove semicolon before KeyToggleFSR and try to press F3 to toggle it on/off so you can spot the difference. Based on your logs, it kinda works but it could stopped when you switched settings.  You shouldn't see MSAA: 1065353216 values, normal are 0, 2, 4, 8. I recommend you to restart the game if you touch any settings.

> Hi, you must activate MSAA, and remove semicolon before hotkey, 114. In game, advanced settings choose scaling factor.
MSAA is not required since the latest update

**Comment by doraimon0** [comment]
> 
> 
> > anyways i just wanted to say that this may work on nvidia old GPU's too but someone with high res monitor could try this out.
> 
> Remove semicolon before KeyToggleFSR and try to press F3 to toggle it on/off so you can spot the difference. Based on your logs, it kinda works but it could stopped when you switched settings. You shouldn't see MSAA: 1065353216 values, normal are 0, 2, 4, 8. I recommend you to restart the game if you touch any settings.
> 
> > Hi, you must activate MSAA, and remove semicolon before hotkey, 114. In game, advanced settings choose scaling factor.
> 
> MSAA is not required since the latest update


Yes, i can confirm it works !!
but weird thing is "FSR Balanced" seems not to work no matter how many i try.
all other modes work fine even perfomance, i tested with diffirent settings FXAA and MSAA. not having any problem with this mod :D

in other words: The GTX660 works fine with this mod :)
