### ISSUE TITLE
Can you make this compatible with LukeRoss00's gta5-real-mod??

### ISSUE THREAD

**Issue by coru182** [NarutoUA/gta5_fsr#16]
Can you make this compatible with LukeRoss00's gta5-real-mod??
https://github.com/LukeRoss00/gta5-real-mod
Given VR is very performance intensive, i'm sure VR users will rejoice with free performance. :D

**Comment by NarutoUA** [comment]
Try next:
1. Rename my mod d3d11.dll to d3d11_fsr.dll
1. Open d3dx.ini (from gta5-real-mod)
2. Find `;proxy_d3d11=d3d11_helix.dll` and change it to `proxy_d3d11=d3d11_fsr.dll`
There should be 2 .dll files in game folder: d3d11.dll from gta5-real-mod and d3d11_fsr.dll from this mod

**Comment by Odgipy** [comment]
For information, I've also the REDUX mod installed

**Comment by coru182** [comment]
Thanks for the fast reply, i did try that, but it didnt seem to work due to
the settings needed for the VR MOD to work.
I did ask the MOD dev and he replied the following

On first look, it doesn't seem like it would work. The mod you linked to
uses FSR to recover from a Frame scaling which is less than 1 (they list
1:2 to 5:6 ratios) with a better quality than GTA V internal upscaler can
provide. My mod uses Frame scaling to make the game natively draw an image
with a higher resolution than the output window: no upscaling is ever
involved.

Is there any way you can tweak your mod for it to also work with the VR mod
frame scaling settings?

Thanks!!!!

**Comment by NarutoUA** [comment]
I have no plans adding compatibility with this vr mod. Its easier to its author to add FSR than me figuring out how this closed-source mod works.

**Comment by Ilham200547** [comment]
helpers/d3d11_helper.h
