### ISSUE TITLE
Works on 940MX?

### ISSUE THREAD

**Issue by miguel2002-upb** [NarutoUA/gta5_fsr#17]
I did all the steps but I had to do the DebugView part, but when I start the game I get "Failed to create EASU shader", what should I do? or my graphics card is not compatible?

**Comment by NarutoUA** [comment]
Your GPU is incompatible

**Comment by NarutoUA** [comment]
... or you are running in DirectX 10/10.1 mode. If it happens in DirectX11 then yes, your gpu is is not compatible
