### ISSUE TITLE
Not working on APU Ryzen 2400G

### ISSUE THREAD

**Issue by kassindornelles** [NarutoUA/gta5_fsr#2]
both the .dll and .ini files are next to the game .exe file, i'm using a Ryzen 2400G APU and feels like it's failing to inject the .dll into the game (failing to load the library maybe?)
Pressing F3 for ultra quality mode (while using the correct render scale) also does nothing, if you have any logging feature please make me aware of it.

Some system info:
AMD Radeon Software: 21.6.2 (FSR compatible, at least that's what AMD says, even tho FSR is just two shaders...)
CPU: Ryzen 2400G with Radeon Graphics
8 GB RAM
2 GB DDR4 for Vega 11

**Comment by NarutoUA** [comment]
Should be fixed in 1.0.2
Please reply if it works

**Comment by EricPlayZ** [comment]
I got a 2200G APU, seems to work perfectly fine for me after the 1.0.2 update. Thanks mate! The game runs at smooth constant over 60 FPS now and looks very nice as well.
