### ISSUE TITLE
Mod stops working when using a weapon in first person perspective

### ISSUE THREAD

**Issue by Mysticx28** [NarutoUA/gta5_fsr#20]
While playing GTA:O i noticed that using this mod (1.0.2) while in FPP with a gun and running the mod stopped functioning properly, only way to stop this bug was running without a gun in my hands or whenever i stopped running (while in first person) or just change to third person view which would work without this problem. i left my settings.mxl in here just in case and if you want video i can show you.

**Comment by Mysticx28** [comment]
I will leave a link for a video just in case: https://www.youtube.com/watch?v=Qbgc95kYAEw

**Comment by NarutoUA** [comment]
Hello. Looks like you forgot to attach settings.xml. I also need you to update to the latest version (1.0.3) and attach logs while trying to reproduce this issue again. (check [Troubleshooting](https://github.com/NarutoUA/gta5_fsr#troubleshooting) section)

**Comment by Mysticx28** [comment]
Hello again, i will try to attach the files again. About the bug i noticed that on this version i get micro stutters now when i try to test this.
[DESKTOP-DCJ83T7.LOG](https://github.com/NarutoUA/gta5_fsr/files/6780382/DESKTOP-DCJ83T7.LOG)
[settings.txt](https://github.com/NarutoUA/gta5_fsr/files/6780383/settings.txt)

**Comment by NarutoUA** [comment]
Thanks for your feedback. I was able to reproduce it with your settings. There is definitely some ingame option which causes this bug. You should see "Updated some resources" spam in your log so you can play around game settings until I fix it.

**Comment by Mysticx28** [comment]
Ok, ill do that! if i find something i will let you know.

**Comment by NarutoUA** [comment]
I didn't find that bugged setting but I fixed the problem. I will try to release update ASAP but I want check and fix Rage.MP compatibility first.
