### ISSUE TITLE
Not working on AMD RX 570

### ISSUE THREAD

**Issue by lucasfdr** [NarutoUA/gta5_fsr#23]
Hey there.

Tried to all released versions (1.01 to 1.03), but none worked. Tried using the debug mode (on version 1.02), pressing F3 button (on version 1.03) and nothing seems to trully enabling it, even if the debugger shows it's running. Even if there's some image degradation, the FPS doesn't increases at all. Actually, there is even some FPS drops.

There's a Youtube video with the same issue using a similar graphics card. You may check it here:
https://youtu.be/XYBWYi5G054

Please, let me know about anything I may do to help solving it. I became a huge fan of your work

Game version: Epic Games Store
My specs:
GPU: XFX RX 570 4GB (Stock)
CPU: Xeon x3440 2.5ghz (Stock)
Mem: 2x4GB ddr3 1333mhz
Mobo: Phitronics H55-M

**Comment by NarutoUA** [comment]
Debug mode is only for printing messages to DebugView, it may decrease performance. FPS boost is achieved by switching frame scaling mode to lower than your real resolution. This mod just makes it less blurry (this is how FSR works). F3 button works only if you enable it in config file.

**Comment by lucasfdr** [comment]
I Used debug mode only on 1.02 version. The current version (1.03), I didn't.
Yeah, I changed the upscaling mode. Here are the results for:

Normal:
![Normal](https://user-images.githubusercontent.com/22638670/125064123-af868400-e086-11eb-8bd2-d66511da4fb0.png)

Quality (0.667):
![Quality](https://user-images.githubusercontent.com/22638670/125064226-ce851600-e086-11eb-8dbc-944b4cc47b0e.png)

Performance (0.500):
![Performance](https://user-images.githubusercontent.com/22638670/125064262-d93fab00-e086-11eb-8911-4624f9d23746.png)

All with MSAA (and FXAA) OFF .

**Comment by NarutoUA** [comment]
Well, looks like your game is bottlenecked by CPU. You can delete d3d11.dll and see the same performance with different scaling modes.

**Comment by lucasfdr** [comment]
Just tested it removing d3d11.dll and, well, you are right... This CPU sucks. Will upgrade to Rysen 3500x soon. 

I will contact the guy from the video I mentioned, see if he still getting the issue and wich is his CPU.

Many thanks for your support.
