### ISSUE TITLE
NVE Support 

### ISSUE THREAD

**Issue by Extendo762** [NarutoUA/gta5_fsr#26]
the enb won't work, I made sure to follow all the steps,

**Comment by NarutoUA** [comment]
Because most likely NVE also uses reshade which is not compatible with this mod yet

**Comment by Extendo762** [comment]
it uses enb

**Comment by Extendo762** [comment]
using reshade is optional

**Comment by NarutoUA** [comment]
if you game folder contains dxgi.dll then it won't work

**Comment by Adeliwyr** [comment]
Hey, fellow NVE user here also, 
I checked we do no have dxgi.dll only an enb preset. No reshade. 
Modifying the enblocal.ini makes FiveM not launching if you set the following to true
"InitProxyFunctions=false"

**Comment by Adeliwyr** [comment]
These are the only files we add to the gta v directory 
![screen](https://user-images.githubusercontent.com/40461613/125168899-09329f80-e1a8-11eb-9eff-dfcac2480638.png)

**Comment by NarutoUA** [comment]
Try next:
1. Get the latest version (1.0.4)
2. Rename d3d11.dll (enb) to d3d11_enb.dll
3. Copy d3d11.dll (fsr) to game folder
4. Open gta5_fsr.ini and set:
```
[PROXY]
EnableProxyLibrary=true
InitProxyFunctions=true
ProxyLibrary=d3d11_enb.dll
```

**Comment by Adeliwyr** [comment]
It is in fact working ! Thanks a lot 👍

**Comment by Snipy44** [comment]
Hello, not work for me, my ENB dont want start
