### ISSUE TITLE
Older GTA V versions (and old Nvidia GPUs)

### ISSUE THREAD

**Issue by Wasmachineman-NL** [NarutoUA/gta5_fsr#28]
Does this work on older GTA V versions? I'm still on 1.48 because it's modded to high holy hell and I can't be arsed to upgrade.

Bonus question: I tried your mod on a Quadro 5000M (=GTX 465 DT basically) but it seems it's not working under Fermi unfortunately: https://www.youtube.com/watch?v=U4ftnb0pLy8

**Comment by NarutoUA** [comment]
There is Troubleshooting section you did not read. No logs = no help.
