### ISSUE TITLE
nexusmods.

### ISSUE THREAD

**Issue by SuperVargen** [NarutoUA/gta5_fsr#37]
Hi. I am new to github. I register just to contact you @NarutoUA.
 I could not find find a way to contact you. I just fund this, and it is not exactly optimal but i hope you read it.
I posted your GTA 5 FSR as a mod on nexusmods. Of course with all credits to you. First thing i have poster there.
I hope that is alright with you. If not, please let me know on nexusmods and i will delete it.

I think this mod is amazing and the world should knew about it. Thank you for your work.  

Here are the link to nexusmods. https://www.nexusmods.com/gta5/mods/362?tab=description

Regards.

**Comment by NarutoUA** [comment]
Its OK
