### ISSUE TITLE
does not work on gtx 1050 2gb 

### ISSUE THREAD

**Issue by Tochiev500** [NarutoUA/gta5_fsr#41]
Doesn't work on my gtx 1050 2gb but works in the new terminator, my pc ryzen 2500y gtx 1050 2gb 12 ram

**Comment by NarutoUA** [comment]
no logs = no help

**Comment by Tochiev500** [comment]
![Снимок экрана (4)](https://user-images.githubusercontent.com/87585043/126060046-471cde2a-3f28-4e5b-ad23-b5d2a41920da.png)
sorry forgot to add

**Comment by NarutoUA** [comment]
Try fullscreen mode. Something causing mod to reload frequently and I dont know what it is.

**Comment by Tochiev500** [comment]
Why is this happening ? What do you think is the reason for this?

**Comment by Tochiev500** [comment]
should i hope it works with a new patch ?
