### ISSUE TITLE
Not working for fivem

### ISSUE THREAD

**Issue by J3X2BZ** [NarutoUA/gta5_fsr#42]
When i go to my graphics nothing shows up for like this step "Go to ingame Advanced Graphics settings and set Frame scaling mode:
0.5x - Performance Mode
0.667x - Balanced Mode
0.75x - Quality Mode
0.883x - Ultra Quality Mode
"
These settings dont show up i attched my log file please someone help me?

I attached my log file
[log fsr.LOG](https://github.com/NarutoUA/gta5_fsr/files/6836554/log.fsr.LOG)

My PC configuration:
CPU: Intel Core i7-4770 3.40GHZ
GPU: NVIDIA Geforce GTX 1060 6Gb
RAM: 8gb (4gbx2) Dual Channel

Game is launched through Epic Games.

**Comment by NarutoUA** [comment]
Read README again

**Comment by J3X2BZ** [comment]
I have, read it multiple times

**Comment by NarutoUA** [comment]
Change Graphics -> Render Resolution instead of Advanced Graphics -> Frame scaling mode

**Comment by J3X2BZ** [comment]
where is frame scallign mode i dont see it

**Comment by NarutoUA** [comment]
Ok I am done, its impossible to help you.

**Comment by J3X2BZ** [comment]
lol please
