### ISSUE TITLE
Failed to create EASU texture

### ISSUE THREAD

**Issue by skotinkaa** [NarutoUA/gta5_fsr#45]
Привет, сделал всё по инструкции, установив последнюю версию мода, но он не работает.
[2500] GTA5_FSR: Updating resources... Src: [1600x900]->[1600x900], Dst: [1920x1080]->[1920x1080]	
[2500] GTA5_FSR: Failed to create EASU texture
В Дебуге выдаёт данную ошибку при отрисовке каждого нового кадра. Пытался менять разрешение, в окне/полном экранном режиме, безуспешно.
[logs.LOG](https://github.com/NarutoUA/gta5_fsr/files/6844033/logs.LOG)
[settings.txt](https://github.com/NarutoUA/gta5_fsr/files/6844037/settings.txt)
ПК:
cpu: TripleCore AMD Athlon II X3 435, 2900MHz
gpu: nVIDIA GeForce GT 440
mem: 8 gb

**Comment by skotinkaa** [comment]
Почитав проблемы людей я нашел ответ, прости если занял время.

**Comment by XIVIX134** [comment]
What was the answer pls?

**Comment by skotinkaa** [comment]
Video card does not support fsr

**Comment by XIVIX134** [comment]
It should work since ppl are running it under 10 series gpus
