### ISSUE TITLE
Not working on RX 5600XT

### ISSUE THREAD

**Issue by Iaonnis** [NarutoUA/gta5_fsr#5]
Tried normal method and ENB, neither did work

**Comment by NarutoUA** [comment]
Try to enable MSAA in settings.

**Comment by NarutoUA** [comment]
Should be fixed in 1.0.2
Please reply if it works

**Comment by Iaonnis** [comment]
Now everything is working on RX 5600XT, but on 3200U (Vega 3) only Performance and Quality seems to work, Ultra Quality and Balanced doesnt work at all, and have no idea at all why, if you want a log or something, tell me on which way can I do it, since I'm not familiar with GTA V modding, thanks for you work!

**Comment by NarutoUA** [comment]
Check [this](https://github.com/NarutoUA/gta5_fsr#troubleshooting) section for log instruction
