### ISSUE TITLE
Not working with RX 550

### ISSUE THREAD

**Issue by Fanax1k** [NarutoUA/gta5_fsr#53]
[DESKTOP-JNAK1JM.LOG](https://github.com/NarutoUA/gta5_fsr/files/6909409/DESKTOP-JNAK1JM.LOG)
[settings.xml.log](https://github.com/NarutoUA/gta5_fsr/files/6909410/settings.xml.log)

Hi, tried four different machines with RX 550 2GB, noones accepting FSR. Using Epic Games Launcher.

**Comment by NarutoUA** [comment]
But logs say it works

**Comment by Fanax1k** [comment]
Available Frame Scaling Modes:
0.500
0.667
0.750
0.834
1.250
1.500
1.750
2.000
2.500

There's no 0.883 to choose.

**Comment by NarutoUA** [comment]
There is a typo in readme. 0.883 is 0.833 or 0.834.

**Comment by Fanax1k** [comment]
Alright, thanks :)
