### ISSUE TITLE
Failed to create EASU shader

### ISSUE THREAD

**Issue by diablo488** [NarutoUA/gta5_fsr#60]
[COREI7.LOG](https://github.com/NarutoUA/gta5_fsr/files/7015102/COREI7.LOG)
I made the xml to txt bc i couldn't send it
[settings.txt](https://github.com/NarutoUA/gta5_fsr/files/7015107/settings.txt)

PC config
i7 3770
8gb ram
Intel hd 4000 (no external gpu)
1366*768 res monitor

**Comment by NarutoUA** [comment]
I can't fix it, your GPU is too old
