### ISSUE TITLE
Has anyone been banned in online mode for using this extension?

### ISSUE THREAD

**Issue by Mirr0ch1** [NarutoUA/gta5_fsr#67]
I'm going to give it a go. Stay tuned.

**Comment by NarutoUA** [comment]
Noone got banned for almost a year as far as I know, at least nobody reported to me that he was banned for this mod

**Comment by sapioit** [comment]
You could write in the Readme that you want people to report to you if they get banned for using it in online, just in case, so you can add that as a warning if it ever does happen.
