### ISSUE TITLE
Please update to `FSR 2.1` !!!

### ISSUE THREAD

**Issue by sapioit** [NarutoUA/gta5_fsr#76]
FidelityFX Super Resolution version 2.1 was released recently. Please update this mod to either use the FSR 2.1 code, or to let us use the latest FSR DLL released (so you don't need to update the mod for each new version of FSR).

**Comment by NarutoUA** [comment]
fsr 2.1 does not support DirectX 11

**Comment by sapioit** [comment]
Thanks for answering so quickly! Is there no newer version of FSR which suppors DX11?
