### ISSUE TITLE
New technology superior to FSR, Intel XeSS compatible with all games with TXAA

### ISSUE THREAD

**Issue by boludoz** [NarutoUA/gta5_fsr#81]
I've been comparing FSR with DLSS and Intel XeSS, Intel XeSS looks almost the same at DLSS level, if I'm not mistaken it supports all games with TXAA (I think it's the same as TAA). Maybe you can adapt it to GTA V, you are the only one who has the ability to do it. Technically, TAA must be replaced by XeSS.

![Intel-xess.jpg](https://user-images.githubusercontent.com/11653030/196041257-84fffbce-ffe1-46c4-8635-156eac800a38.jpg)

This in turn is combined with the rescaling, it's a kind of AI, which removes the jagged edges of the rescaling.

https://github.com/intel/xess

**Comment by NarutoUA** [comment]
XeSS does not support DirectX 11
