### ISSUE TITLE
Does not work with reshade AND enb

### ISSUE THREAD

**Issue by blankuserrr** [NarutoUA/gta5_fsr#93]
title

**Comment by Snipy44** [comment]
you found a solution ?

**Comment by RedGreenBlue09** [comment]
Got them working. Here's how: 
1. Name the files: 
ReShade: `dxgi.dll` 
ENBSeries: `d3d11_enb.dll` 
GTA5_FSR: `d3d11.dll`

2. Set this in `enblocal.ini`: 
```
EnableProxyLibrary=true
InitProxyFunctions=false
ProxyLibrary=d3d11.dll
```

3. Set this in `gta5_fsr.ini`:
```
EnableProxyLibrary=true
InitProxyFunctions=true
ProxyLibrary=d3d11_enb.dll
```

Done! Got all of them working at the same time (checked DebugView).

**Comment by ghost** [comment]
> 

Does this also work in FiveM?

**Comment by RedGreenBlue09** [comment]
> > 
> 
> Does this also work in FiveM?

Try it yourself and report the result here to also help people having the same question. Also, other DLLs can be loaded by using some injector like ENB Injector for instance. Didn't tested that though.

**Comment by RedGreenBlue09** [comment]
Seems like it also depends on your machine, so my method might not work for everyone.

**Comment by Snipy44** [comment]
> 1. GTA5_FSR: `d3d11.dll`

![image](https://github.com/NarutoUA/gta5_fsr/assets/3805333/65c3bc55-05f8-4604-859b-1466852611b3)

Look is not work, d3d11_enb error 126

**Comment by Snipy44** [comment]
is not work on fivem is that the problem :)

**Comment by RedGreenBlue09** [comment]
> 

Your error is ERROR_MOD_NOT_FOUND. You might need latest ENB and ReShade version.

**Comment by RedGreenBlue09** [comment]
Someone suggested putting ENB files into your FiveM plugins folder. IDK how that work.

**Comment by skylide** [comment]
> EnableProxyLibrary=true
> InitProxyFunctions=true
> ProxyLibrary=d3d11_enb.dll

i work in sp

**Comment by Snipy44** [comment]
My ENB start now but it's impossible to open menu, any idea ?
![image](https://github.com/NarutoUA/gta5_fsr/assets/3805333/15f5a8dd-b398-4d2e-ae9e-6e1199e5b47b)

**Comment by RedGreenBlue09** [comment]
I don't know. Check the settings in enblocal.ini then.

**Comment by Snipy44** [comment]
yes of course, but is work after rename to d3d11 and remove fsr, i dont understand why is not work after install fsr and d3d11_enb.dll
